<?php
/**
* @file
* Lets users add private annotations to nodes.
*
* Adds a text field when a node is displayed
* so that authenticated users may make notes.
*/

/**
* Implements hook_node_load()
*/
function barra_gov_node_load($nodes, $types) {
  $color = variable_get('barra_gov_color');
  drupal_add_css(drupal_get_path('module', 'barra_gov') . '/css/style-' . $color . '.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  
}

/**
 * Implements hook_page_build().
 */
function barra_gov_page_build(&$page) {
  
  // For some reason with Overlay enabled we get an empty $page, so just fail this case.
  // TODO: traduzir - No meu caso o front page nao tem content
  if (!isset($page['content']) && ( !drupal_is_front_page() ) ) {
    return;
  }

  // We are on a node detail page.
  if ($node = menu_get_object('node', 1) && arg(2) == NULL) {
    // Force to rebuild the sorting
    $page['page_top']['#sorted'] = FALSE;
    
    $page['page_top'] = array(
        '#markup' => '<!-- Barra do Governo  -->
        <div id="barra-brasil">
            <div class="barra">
                <ul>
                    <li><a href="http://www.acessoainformacao.gov.br" class="ai" title="Acesso à informação">www.sic.gov.br</a></li>
                    <li><a href="http://www.brasil.gov.br" class="brasilgov" title="Portal de Estado do Brasil">www.brasil.gov.br</a></li>
                </ul>
            </div>
        </div>',
    );
    
  }
}

/*
 * Implementação do hook_menu()
 */
function barra_gov_menu(){
  $items['admin/config/barra_gov'] = array(
      'title' => 'Barra do Governo',
      'description' => 'Ajusta as opções do modulo barra_gov',
      'position' => 'right',
      'weight' => -5,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('administer site configuration'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module','system'),
  );
  
  $items['admin/config/barra_gov/settings'] = array(
      'title' => 'Configurações visuais',
      'description' => 'Alterar o comportamento visual de Barra do Governo do Brasil',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barra_gov_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'barra_gov.admin.inc',
  );
  
  return $items;  
}



